version = 0.1
[sandbox]
[sandbox.deploy]
[sandbox.deploy.parameters]
stack_name = "sam-app-prototype"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qfefsvtgmd38"
s3_prefix = "sam-app-prototype"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = false
image_repositories = []
